"""
Reports Center component.

Displays downloadable reports with Top 20 company rankings.
"""

import streamlit as st


def render_reports_center(results: list[dict] | None = None) -> None:
    """
    Render the Reports Center with downloadable reports.

    Args:
        results: List of company result dicts with rankings and scores
    """

    # Top 20 Company Report Table - FIRST
    st.markdown(
        """
        <div style="font-size: 1.25rem; font-weight: 600; margin-bottom: 0.75rem;">Top 20 Company Report</div>
        """,
        unsafe_allow_html=True,
    )

    with st.container(border=True):
        # Table with results
        if results:
            import pandas as pd

            df = pd.DataFrame(
                [
                    {
                        "Rank": r.get("rank", "—"),
                        "Ticker": r.get("ticker", "—"),
                        "Name": r.get("company_name", "—"),
                        "Segment": r.get("ai_factory_segment", "—"),
                        "Moat": f"{r.get('moat_score', 0):.1f}",
                        "Margin": f"{r.get('margin_score', 0):.1f}",
                        "CAGR": f"{r.get('growth_cagr_3yr', 0) * 100:.1f}",
                        "TAFGS": f"{r.get('tafgs_score', 0):.2f}",
                    }
                    for r in results[:20]
                ]
            )

            st.dataframe(df, width="stretch", hide_index=True, height=400)
        else:
            st.info("No data available. Run deep search to view results.")

    st.write("")  # Spacer

    # AI Factory Growth Report section with downloads
    with st.container(border=True):
        st.markdown(
            """
            <div style="font-size: 1.25rem; font-weight: 600; margin-bottom: 1rem;">AI Factory Growth Report</div>
            """,
            unsafe_allow_html=True,
        )

        # Generate report content
        if results and len(results) > 0:
            # Get report markdown from session state (generated by LangGraph Report Agent)
            report_markdown = (
                st.session_state.get("result", {}).get("report_markdown")
                if isinstance(st.session_state.get("result"), dict)
                else None
            )

            # Parse Key Insights and Competitive Notes from LangGraph report_markdown
            key_insights_content = []
            competitive_notes_content = []

            if report_markdown:
                # Extract Key Insights & Competitive Notes section
                lines = report_markdown.split("\n")
                in_insights_section = False

                for line in lines:
                    if "### Key Insights & Competitive Notes" in line:
                        in_insights_section = True
                        continue

                    if in_insights_section and line.strip():
                        # Parse bullet points for companies
                        if line.strip().startswith("- **"):
                            # Main insight line (moat narrative)
                            key_insights_content.append(line.strip())
                        elif line.strip().startswith("- *Risk Factors*:"):
                            # Risk factors line
                            competitive_notes_content.append(line.strip())

            # If no report_markdown, generate basic report
            if not report_markdown:
                top_company = results[0]
                avg_tafgs = sum(r.get("tafgs_score", 0) for r in results) / len(results)
                segment_counts: dict[str, int] = {}
                for r in results:
                    seg = r.get("ai_factory_segment", "unknown")
                    segment_counts[seg] = segment_counts.get(seg, 0) + 1

                dominant_segment = (
                    max(segment_counts, key=segment_counts.get)
                    if segment_counts
                    else "compute"
                )

                # Build markdown report (fallback if LangGraph didn't generate one)
                report_lines = [
                    "# AI Factory Growth Engine Report\n\n",
                    f"**Analysis Date:** {st.session_state.get('analysis_date', 'Recent')}\n\n",
                    f"**Companies Analyzed:** {len(results)}\n\n",
                    f"**Average TAFGS Score:** {avg_tafgs:.2f}\n\n",
                    "## Executive Summary\n\n",
                    f"Analysis of {len(results)} companies across the AI Factory infrastructure value chain reveals ",
                    f"**{top_company.get('ticker')}** ({top_company.get('company_name')}) as the highest-ranked ",
                    f"opportunity with a TAFGS score of **{top_company.get('tafgs_score', 0):.2f}**.\n\n",
                    f"The **{dominant_segment}** segment dominates the portfolio with {segment_counts.get(dominant_segment, 0)} ",
                    f"companies, reflecting the critical role of {dominant_segment} infrastructure in AI datacenter buildouts.\n\n",
                    "## Top 20 Companies\n\n",
                    "| Rank | Ticker | Company Name | Segment | Moat | Margin | CAGR % | TAFGS |\n",
                    "|------|--------|--------------|---------|------|--------|--------|-------|\n",
                ]

                for r in results[:20]:
                    report_lines.append(
                        f"| {r.get('rank', '—')} | {r.get('ticker', '—')} | {r.get('company_name', '—')} | "
                        f"{r.get('ai_factory_segment', '—')} | {r.get('moat_score', 0):.1f}/5 | "
                        f"{r.get('margin_score', 0):.1f}% | {r.get('growth_cagr_3yr', 0) * 100:.1f}% | "
                        f"{r.get('tafgs_score', 0):.2f} |\n"
                    )

                report_lines.append("\n### Key Insights & Competitive Notes\n\n")

                # Use company narratives if available
                for r in results[:20]:
                    if r.get("moat_narrative"):
                        report_lines.append(
                            f"- **{r.get('ticker')}**: {r.get('moat_narrative')}\n"
                        )
                        key_insights_content.append(
                            f"- **{r.get('ticker')}**: {r.get('moat_narrative')}"
                        )
                    if r.get("risk_notes"):
                        report_lines.append(
                            f"  - *Risk Factors*: {r.get('risk_notes')}\n"
                        )
                        competitive_notes_content.append(
                            f"  - *Risk Factors*: {r.get('risk_notes')}"
                        )

                report_markdown = "".join(report_lines)

            # Store in session state for download
            st.session_state.report_content = report_markdown

            # Download buttons - only .md and .txt
            col1, col2, col3, col_spacer = st.columns([1.2, 1.2, 1.6, 6.2])

            with col1:
                st.download_button(
                    label="Download .md",
                    data=report_markdown,
                    file_name="ai_factory_report.md",
                    mime="text/markdown",
                    use_container_width=True,
                )

            with col2:
                st.download_button(
                    label="Download .txt",
                    data=report_markdown,
                    file_name="ai_factory_report.txt",
                    mime="text/plain",
                    use_container_width=True,
                )

            with col3:
                # Use pyperclip alternative - streamlit clipboard
                st.download_button(
                    label="📋 Copy Report",
                    data=report_markdown,
                    file_name="ai_factory_report.md",
                    mime="text/markdown",
                    use_container_width=True,
                )

        else:
            st.info("No data available. Run deep search to view results.")

        st.write("")  # Spacer

        # Key Insights Section - from LangGraph Report Agent
        if results and key_insights_content:
            st.markdown(
                """
                <div style="font-size: 1.125rem; font-weight: 600; margin-bottom: 0.75rem;">Key Insights</div>
                """,
                unsafe_allow_html=True,
            )

            with st.container(border=True):
                # Display insights from LangGraph report (moat narratives)
                for insight in key_insights_content:
                    st.markdown(insight)

            st.write("")  # Spacer

            # Competitive Notes Section - from LangGraph Report Agent
            st.markdown(
                """
                <div style="font-size: 1.125rem; font-weight: 600; margin-bottom: 0.75rem;">Competitive Notes</div>
                """,
                unsafe_allow_html=True,
            )

            with st.container(border=True):
                # Display competitive notes from LangGraph report (risk factors)
                if competitive_notes_content:
                    for note in competitive_notes_content:
                        st.markdown(note)
                else:
                    st.info("No specific risk factors identified for top companies.")

        elif results:
            # Fallback if no parsed content available
            st.markdown(
                """
                <div style="font-size: 1.125rem; font-weight: 600; margin-bottom: 0.75rem;">Key Insights</div>
                """,
                unsafe_allow_html=True,
            )

            with st.container(border=True):
                st.info("No data available. Run deep search to view results.")
